version: '3'

services:
  greenfinch.newsletter.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  greenfinch.newsletter.web.mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
networks:
  default:
    external:
      name: nat

