language: csharp
dist: trusty
mono: none
dotnet: 2.1
install:
- dotnet restore
script:
- dotnet build
- dotnet test ../tests/Greenfinch.Newsletter.Web.Core.Tests/Greenfinch.Newsletter.Web.Core.Services.Tests